---
stages:
  train:
    cmd: >-
      accelerate launch submodules/diffusers/examples/dreambooth/train_dreambooth.py 
      --pretrained_model_name_or_path="${pretrained_model}"
      --class_data_dir="${class.dir}"
      --class_prompt="${class.prompt}" 
      --num_class_images="${class.count}" 
      --instance_data_dir="${instance.dir}"
      --instance_prompt="${instance.prompt}" 
      --output_dir=src/train/model 
      --with_prior_preservation 
      --prior_loss_weight=1.0 
      --resolution=512 
      --train_batch_size=1 
      --gradient_accumulation_steps=1 
      --learning_rate="${learning_rate}" 
      --lr_scheduler="constant" 
      --lr_warmup_steps=0 
      --max_train_steps="${training_steps}" 
      --gradient_checkpointing 
      --mixed_precision=fp16 
      --use_8bit_adam
    params:
      - pretrained_model
      - class.dir
      - class.prompt
      - class.count
      - instance.dir
      - instance.prompt
      - learning_rate
      - training_steps
    outs:
      - src/train/model/${training_steps}
  infer:
    cmd: |
       src/infer/infer.py ${training_steps}
       src/infer/infer.py ${training_steps} -p prompts2
       src/infer/infer.py ${training_steps} -p prompts3
       src/infer/infer.py ${training_steps} -p prompts4
       src/infer/infer.py ${training_steps} -p prompts5
    deps:
      - src/train/model/${training_steps}
    plots:
      - src/infer/output
