---
stages:
  train:
    cmd: >-
      train/train.sh
      ${instance_dir}
      ${instance_prompt}
      ${class_prompt}
      ${class_count}
      ${learning_rate}
      ${training_steps}
    params:
      - instance_dir
      - instance_prompt
      - class_prompt
      - class_count
      - learning_rate
      - training_steps
    outs:
      - data/model/${training_steps}
  infer:
    cmd: >-
       infer/infer.py ${training_steps}
    deps:
      - data/model/${training_steps}
    plots:
      - output
