---
pretrained_model: CompVis/stable-diffusion-v1-4
class:
  dir: src/train/data/classes/man/228
  prompt: man
  count: 228
instance:
  dir: src/train/data/instances/kieran4
  prompt: kokieran
learning_rate: 1e-6
training_steps: 2160
