---
pretrained_model: CompVis/stable-diffusion-v1-4
class:
  dir: src/train/data/classes/cat/800
  prompt: cat
  count: 800
instance:
  dir: src/train/data/instances/joyce
  prompt: kostancat
learning_rate: 3e-06
training_steps: 800
