---
pretrained_model: CompVis/stable-diffusion-v1-4
class:
  prompt: cat
  count: 200
instance:
  prompt: kowilfred
learning_rate: 3e-06
training_steps: 2800
infer:
  instance: kowilfred
  prompts:
    - cat-prompts
    - cat-prompts2
    - cat-prompts3
