---
pretrained_model: CompVis/stable-diffusion-v1-4
class:
  prompt: man
  count: 228
instance:
  prompt: kokieran
learning_rate: 5e-06
training_steps: 100
infer:
  instance: kokieran man
  prompts:
    - prompts
    - prompts2
    - tough-ones
    - tough-ones2
