---
pretrained_model: CompVis/stable-diffusion-v1-4
class:
  dir: src/train/data/classes/man/4400
  prompt: man
  count: 4400
instance:
  dir: src/train/data/instances/kieran3and4
  prompt: kokieran
learning_rate: 1e-06
training_steps: 8280
