---
version: "3"
services:
  mlflow:
    image: public.ecr.aws/b1h6u3t2/kieran-diffusers-mlflow:1
    build:
      context: .
    env_file:
      - .env.aws
      - .env.db
    ports:
      - 5001:5000
    # entrypoint: /bin/bash
    volumes:
      - ./:/data
    working_dir: /data
    platform: linux/amd64
