---
- name: Get xformers
  ansible.builtin.git:
    repo: https://github.com/facebookresearch/xformers.git
    dest: "/tmp/xformers"
    recursive: yes
  become: true
  become_user: "{{ username }}"
  tags:
    - sd

- name: SD Conda Env
  copy:
    src: ./home/sd.yml
    dest: "/home/{{ username }}/sd.yml"
    owner: "{{ username }}"
    group: wheel
  become: true
  tags:
    - sd
    - this
  notify:
    - Install SD Conda Env
