---
- name: kieran-diffusers
  git:
    repo: https://github.com/kieran-ohara/kieran-diffusers.git
    dest: "/home/{{ username }}/kieran-diffusers"
    recursive: yes
  become: true
  become_user: "{{ username }}"
  tags:
    - sd

- name: Install SD Conda Env
  shell:
    cmd: |
      source /opt/conda/etc/profile.d/conda.sh
      conda env create --file sd.yml
  become: true
  become_user: "{{ username }}"
  args:
    chdir: "/home/{{ username }}/kieran-diffusers"

- name: Install xformers - THIS TAKES A LONG TIME!
  shell:
    cmd: |
      source /opt/conda/etc/profile.d/conda.sh
      conda activate sd
      CUDA_HOME=/usr/local/cuda TORCH_CUDA_ARCH_LIST=7.5 pip install -e .
  become: true
  become_user: "{{ username }}"
  args:
    chdir: "/home/{{ username }}/kieran-diffusers/submodules/xformers"
