version: '3'
services:
  mlflow:
    image: public.ecr.aws/b1h6u3t2/kieran-diffusers-mlflow:latest
    build:
      context: .
    env_file: .env
    ports:
      - 5001:5000
    # entrypoint: /bin/bash
